In [1]:
import numpy as np

In [2]:
np.__version__

'1.16.5'

In [3]:
!pip install --upgrade numpy

Requirement already up-to-date: numpy in e:\install softwares\anac6nda\lib\site-packages (1.16.5)


In [4]:
np.__version__

'1.16.5'

In [5]:
a = np.arange(15).reshape(3, 5)

In [6]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [11]:
a.ndim   #for visualizing dimension of array

2

In [12]:
a.shape    #for checkin dimension/rown and columns of array

(3, 5)

In [13]:
a.size   #show total number of elemnets in array

15

In [14]:
a.dtype

dtype('int32')

In [15]:
a.itemsize     #show size of bytes in each elemnts of array

4

In [19]:
b=np.array([1,2,3])

In [20]:
b.dtype

dtype('int32')

In [21]:
b

array([1, 2, 3])

In [23]:
c=np.zeros((2,3))

In [24]:
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
c=np.ones((3,3))

In [26]:
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.empty((2,2))

array([[5.e-324, 5.e-324],
       [0.e+000, 0.e+000]])

In [28]:
np.arange(5,30,5)

array([ 5, 10, 15, 20, 25])

In [29]:
np.linspace( 0, 2, 9 )

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [31]:
from numpy import pi

In [32]:
x = np.linspace( 0, 2*pi, 100 )

In [33]:
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [34]:
 c = np.arange(24).reshape(2,3,4)

In [35]:
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [36]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [37]:
a=np.array([12,14,16,18])
b=np.arange(4)

In [38]:
b

array([0, 1, 2, 3])

In [39]:
c=a+b

In [40]:
c

array([12, 15, 18, 21])

In [41]:
a-b

array([12, 13, 14, 15])

In [42]:
b-a

array([-12, -13, -14, -15])

In [43]:
a*2

array([24, 28, 32, 36])

In [44]:
a**2

array([144, 196, 256, 324], dtype=int32)

In [45]:
5*np.sin(b)

array([0.        , 4.20735492, 4.54648713, 0.70560004])

In [47]:
b>0

array([False,  True,  True,  True])

In [57]:
a=np.arange(16).reshape(4,4)
b=np.arange(16).reshape(4,4)
a
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [58]:
a+b

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [59]:
a@b

array([[ 56,  62,  68,  74],
       [152, 174, 196, 218],
       [248, 286, 324, 362],
       [344, 398, 452, 506]])

In [61]:
a*=2

In [62]:
a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [67]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,pi,3)

In [68]:
a.dtype

dtype('int32')

In [69]:
b.dtype

dtype('float64')

In [70]:
c=a+b

In [71]:
c.dtype                        #upcasting

dtype('float64')

In [74]:
a=np.arange(16).reshape(4,4)

In [75]:
a.sum()

120

In [76]:
a.min()

0

In [77]:
a.max()

15

In [78]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [83]:
a.sum(axis=0)             #sum of each colum, 0 means columns and 1 means rows

array([24, 28, 32, 36])

In [84]:
a.sum(axis=1)

array([ 6, 22, 38, 54])

In [85]:
a.min(axis=0)

array([0, 1, 2, 3])

In [86]:
a.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38],
       [12, 25, 39, 54]], dtype=int32)

In [87]:
np.sqrt(a)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335]])

In [88]:
a = np.arange(10)**3

In [89]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [90]:
a[:6:2] = 1000   #starting from 0 index upto 6-1 index is replace every 2nd elemnt with 1000

In [91]:
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729],
      dtype=int32)

In [95]:
a = np.arange(15).reshape(3, 5)

In [96]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [97]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [98]:
a.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [99]:
a.T              #return transpose

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [101]:
a.resize(5,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [105]:
b=np.arange(15).reshape(5,3)

In [106]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [107]:
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [108]:
np.hstack((a,b))

array([[ 0,  1,  2,  0,  1,  2],
       [ 3,  4,  5,  3,  4,  5],
       [ 6,  7,  8,  6,  7,  8],
       [ 9, 10, 11,  9, 10, 11],
       [12, 13, 14, 12, 13, 14]])

In [109]:
np.hsplit(a,3)

[array([[ 0],
        [ 3],
        [ 6],
        [ 9],
        [12]]), array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13]]), array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14]])]

In [110]:
np.hsplit(a,(1,2))

[array([[ 0],
        [ 3],
        [ 6],
        [ 9],
        [12]]), array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13]]), array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14]])]

In [111]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [112]:
b=a

In [113]:
b is a

True

In [114]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])